spring:
  datasource:
    username: root
    password: root
    #mysql 8版本以上的驱动包，需要指定以下时区+***********************************************************************
    url: jdbc:mysql://127.0.0.1:3306/bill?serverTimezone=GMT%2B8
    #mysql 8版本以上指定新的驱动类**********************************************************************************
    driver-class-name: com.mysql.cj.jdbc.Driver
    #引入Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


    # 数据源其他配置, DataSourceProperties中没有相关属性,默认无法绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 25
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

  # redis缓存
  redis:
    #redis服务器地址，这里用本地的redis
    host: 127.0.0.1
    #redis数据库索引，默认是0
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    #redis服务器连接端口，默认是6379
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0

  #配置mybatis相关文件路径，可以使用通配符的方式
mybatis:
  #映射配置文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #核心配置文件路径
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  level:
    com.mengxuegu.springboot.mapper: debug

  #注意：新增 修改页面有生日是Date类型，SpringBoot默认识别是 dd/MM/yyyy 格式
  #但是我们传入的其他格式，如 yyyy-MM-dd ，则需要在配置中修改日期格式

server:
  port: 80
